import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Topo from "@/componentes/Topo/index";
import SecaoCapa from "@/componentes/SecaoCapa/index";
import SecaoProdutos from "@/componentes/SecaoProdutos/index";
import SecaoSobre from "@/componentes/SecaoSobre/index";
import SecaoContatos from "@/componentes/SecaoContatos/index";
import Rodape from "@/componentes/Rodape/index";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Topo />
        <SecaoCapa />
        <SecaoProdutos />
        <SecaoSobre />
        <SecaoContatos/>
        <Rodape />
      </main>
    </>
  );
}
